INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1, 'SW');
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2, 'HW');
INSERT INTO QUIZ (ID, LEVEL, DESCRIPTION, CATEGORY_ID, PARENT_ID) VALUES (1, 1, '1번 문제', 1, NULL);
INSERT INTO QUIZ (ID, LEVEL, DESCRIPTION, CATEGORY_ID, PARENT_ID) VALUES (2, 2, '2번 문제', 1, 1);
INSERT INTO QUIZ (ID, LEVEL, DESCRIPTION, CATEGORY_ID, PARENT_ID) VALUES (3, 2, '3번 문제', 1, 1);
INSERT INTO QUIZ (ID, LEVEL, DESCRIPTION, CATEGORY_ID, PARENT_ID) VALUES (4, 3, '4번 문제', 1, 3);
INSERT INTO QUIZ (ID, LEVEL, DESCRIPTION, CATEGORY_ID, PARENT_ID) VALUES (5, 3, '54번 문제', 1, 3);
INSERT INTO USER (ID, EMAIL, COMPANY, NAME) VALUES (1,'hello@email.com', 'KOSTA', '홍길동');
INSERT INTO USER (ID, EMAIL, COMPANY, NAME) VALUES (2,'hello2@email.com', 'KOSTA2', '홍길동2');
